using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NUlid;
using NodaTime;
using NpgsqlTypes;

namespace CardOverflow.Entity
{
    public enum TimezoneName
    {
        [PgName("Africa/Abidjan")]
        Africa_Abidjan,
        [PgName("Africa/Accra")]
        Africa_Accra,
        [PgName("Africa/Addis_Ababa")]
        Africa_Addis_Ababa,
        [PgName("Africa/Algiers")]
        Africa_Algiers,
        [PgName("Africa/Asmara")]
        Africa_Asmara,
        [PgName("Africa/Asmera")]
        Africa_Asmera,
        [PgName("Africa/Bamako")]
        Africa_Bamako,
        [PgName("Africa/Bangui")]
        Africa_Bangui,
        [PgName("Africa/Banjul")]
        Africa_Banjul,
        [PgName("Africa/Bissau")]
        Africa_Bissau,
        [PgName("Africa/Blantyre")]
        Africa_Blantyre,
        [PgName("Africa/Brazzaville")]
        Africa_Brazzaville,
        [PgName("Africa/Bujumbura")]
        Africa_Bujumbura,
        [PgName("Africa/Cairo")]
        Africa_Cairo,
        [PgName("Africa/Casablanca")]
        Africa_Casablanca,
        [PgName("Africa/Ceuta")]
        Africa_Ceuta,
        [PgName("Africa/Conakry")]
        Africa_Conakry,
        [PgName("Africa/Dakar")]
        Africa_Dakar,
        [PgName("Africa/Dar_es_Salaam")]
        Africa_Dar_es_Salaam,
        [PgName("Africa/Djibouti")]
        Africa_Djibouti,
        [PgName("Africa/Douala")]
        Africa_Douala,
        [PgName("Africa/El_Aaiun")]
        Africa_El_Aaiun,
        [PgName("Africa/Freetown")]
        Africa_Freetown,
        [PgName("Africa/Gaborone")]
        Africa_Gaborone,
        [PgName("Africa/Harare")]
        Africa_Harare,
        [PgName("Africa/Johannesburg")]
        Africa_Johannesburg,
        [PgName("Africa/Juba")]
        Africa_Juba,
        [PgName("Africa/Kampala")]
        Africa_Kampala,
        [PgName("Africa/Khartoum")]
        Africa_Khartoum,
        [PgName("Africa/Kigali")]
        Africa_Kigali,
        [PgName("Africa/Kinshasa")]
        Africa_Kinshasa,
        [PgName("Africa/Lagos")]
        Africa_Lagos,
        [PgName("Africa/Libreville")]
        Africa_Libreville,
        [PgName("Africa/Lome")]
        Africa_Lome,
        [PgName("Africa/Luanda")]
        Africa_Luanda,
        [PgName("Africa/Lubumbashi")]
        Africa_Lubumbashi,
        [PgName("Africa/Lusaka")]
        Africa_Lusaka,
        [PgName("Africa/Malabo")]
        Africa_Malabo,
        [PgName("Africa/Maputo")]
        Africa_Maputo,
        [PgName("Africa/Maseru")]
        Africa_Maseru,
        [PgName("Africa/Mbabane")]
        Africa_Mbabane,
        [PgName("Africa/Mogadishu")]
        Africa_Mogadishu,
        [PgName("Africa/Monrovia")]
        Africa_Monrovia,
        [PgName("Africa/Nairobi")]
        Africa_Nairobi,
        [PgName("Africa/Ndjamena")]
        Africa_Ndjamena,
        [PgName("Africa/Niamey")]
        Africa_Niamey,
        [PgName("Africa/Nouakchott")]
        Africa_Nouakchott,
        [PgName("Africa/Ouagadougou")]
        Africa_Ouagadougou,
        [PgName("Africa/Porto-Novo")]
        Africa_Porto_Novo,
        [PgName("Africa/Sao_Tome")]
        Africa_Sao_Tome,
        [PgName("Africa/Timbuktu")]
        Africa_Timbuktu,
        [PgName("Africa/Tripoli")]
        Africa_Tripoli,
        [PgName("Africa/Tunis")]
        Africa_Tunis,
        [PgName("Africa/Windhoek")]
        Africa_Windhoek,
        [PgName("America/Adak")]
        America_Adak,
        [PgName("America/Anchorage")]
        America_Anchorage,
        [PgName("America/Anguilla")]
        America_Anguilla,
        [PgName("America/Antigua")]
        America_Antigua,
        [PgName("America/Araguaina")]
        America_Araguaina,
        [PgName("America/Argentina/Buenos_Aires")]
        America_Argentina_Buenos_Aires,
        [PgName("America/Argentina/Catamarca")]
        America_Argentina_Catamarca,
        [PgName("America/Argentina/ComodRivadavia")]
        America_Argentina_ComodRivadavia,
        [PgName("America/Argentina/Cordoba")]
        America_Argentina_Cordoba,
        [PgName("America/Argentina/Jujuy")]
        America_Argentina_Jujuy,
        [PgName("America/Argentina/La_Rioja")]
        America_Argentina_La_Rioja,
        [PgName("America/Argentina/Mendoza")]
        America_Argentina_Mendoza,
        [PgName("America/Argentina/Rio_Gallegos")]
        America_Argentina_Rio_Gallegos,
        [PgName("America/Argentina/Salta")]
        America_Argentina_Salta,
        [PgName("America/Argentina/San_Juan")]
        America_Argentina_San_Juan,
        [PgName("America/Argentina/San_Luis")]
        America_Argentina_San_Luis,
        [PgName("America/Argentina/Tucuman")]
        America_Argentina_Tucuman,
        [PgName("America/Argentina/Ushuaia")]
        America_Argentina_Ushuaia,
        [PgName("America/Aruba")]
        America_Aruba,
        [PgName("America/Asuncion")]
        America_Asuncion,
        [PgName("America/Atikokan")]
        America_Atikokan,
        [PgName("America/Atka")]
        America_Atka,
        [PgName("America/Bahia")]
        America_Bahia,
        [PgName("America/Bahia_Banderas")]
        America_Bahia_Banderas,
        [PgName("America/Barbados")]
        America_Barbados,
        [PgName("America/Belem")]
        America_Belem,
        [PgName("America/Belize")]
        America_Belize,
        [PgName("America/Blanc-Sablon")]
        America_Blanc_Sablon,
        [PgName("America/Boa_Vista")]
        America_Boa_Vista,
        [PgName("America/Bogota")]
        America_Bogota,
        [PgName("America/Boise")]
        America_Boise,
        [PgName("America/Buenos_Aires")]
        America_Buenos_Aires,
        [PgName("America/Cambridge_Bay")]
        America_Cambridge_Bay,
        [PgName("America/Campo_Grande")]
        America_Campo_Grande,
        [PgName("America/Cancun")]
        America_Cancun,
        [PgName("America/Caracas")]
        America_Caracas,
        [PgName("America/Catamarca")]
        America_Catamarca,
        [PgName("America/Cayenne")]
        America_Cayenne,
        [PgName("America/Cayman")]
        America_Cayman,
        [PgName("America/Chicago")]
        America_Chicago,
        [PgName("America/Chihuahua")]
        America_Chihuahua,
        [PgName("America/Coral_Harbour")]
        America_Coral_Harbour,
        [PgName("America/Cordoba")]
        America_Cordoba,
        [PgName("America/Costa_Rica")]
        America_Costa_Rica,
        [PgName("America/Creston")]
        America_Creston,
        [PgName("America/Cuiaba")]
        America_Cuiaba,
        [PgName("America/Curacao")]
        America_Curacao,
        [PgName("America/Danmarkshavn")]
        America_Danmarkshavn,
        [PgName("America/Dawson")]
        America_Dawson,
        [PgName("America/Dawson_Creek")]
        America_Dawson_Creek,
        [PgName("America/Denver")]
        America_Denver,
        [PgName("America/Detroit")]
        America_Detroit,
        [PgName("America/Dominica")]
        America_Dominica,
        [PgName("America/Edmonton")]
        America_Edmonton,
        [PgName("America/Eirunepe")]
        America_Eirunepe,
        [PgName("America/El_Salvador")]
        America_El_Salvador,
        [PgName("America/Ensenada")]
        America_Ensenada,
        [PgName("America/Fortaleza")]
        America_Fortaleza,
        [PgName("America/Fort_Nelson")]
        America_Fort_Nelson,
        [PgName("America/Fort_Wayne")]
        America_Fort_Wayne,
        [PgName("America/Glace_Bay")]
        America_Glace_Bay,
        [PgName("America/Godthab")]
        America_Godthab,
        [PgName("America/Goose_Bay")]
        America_Goose_Bay,
        [PgName("America/Grand_Turk")]
        America_Grand_Turk,
        [PgName("America/Grenada")]
        America_Grenada,
        [PgName("America/Guadeloupe")]
        America_Guadeloupe,
        [PgName("America/Guatemala")]
        America_Guatemala,
        [PgName("America/Guayaquil")]
        America_Guayaquil,
        [PgName("America/Guyana")]
        America_Guyana,
        [PgName("America/Halifax")]
        America_Halifax,
        [PgName("America/Havana")]
        America_Havana,
        [PgName("America/Hermosillo")]
        America_Hermosillo,
        [PgName("America/Indiana/Indianapolis")]
        America_Indiana_Indianapolis,
        [PgName("America/Indiana/Knox")]
        America_Indiana_Knox,
        [PgName("America/Indiana/Marengo")]
        America_Indiana_Marengo,
        [PgName("America/Indiana/Petersburg")]
        America_Indiana_Petersburg,
        [PgName("America/Indiana/Tell_City")]
        America_Indiana_Tell_City,
        [PgName("America/Indiana/Vevay")]
        America_Indiana_Vevay,
        [PgName("America/Indiana/Vincennes")]
        America_Indiana_Vincennes,
        [PgName("America/Indiana/Winamac")]
        America_Indiana_Winamac,
        [PgName("America/Indianapolis")]
        America_Indianapolis,
        [PgName("America/Inuvik")]
        America_Inuvik,
        [PgName("America/Iqaluit")]
        America_Iqaluit,
        [PgName("America/Jamaica")]
        America_Jamaica,
        [PgName("America/Jujuy")]
        America_Jujuy,
        [PgName("America/Juneau")]
        America_Juneau,
        [PgName("America/Kentucky/Louisville")]
        America_Kentucky_Louisville,
        [PgName("America/Kentucky/Monticello")]
        America_Kentucky_Monticello,
        [PgName("America/Knox_IN")]
        America_Knox_IN,
        [PgName("America/Kralendijk")]
        America_Kralendijk,
        [PgName("America/La_Paz")]
        America_La_Paz,
        [PgName("America/Lima")]
        America_Lima,
        [PgName("America/Los_Angeles")]
        America_Los_Angeles,
        [PgName("America/Louisville")]
        America_Louisville,
        [PgName("America/Lower_Princes")]
        America_Lower_Princes,
        [PgName("America/Maceio")]
        America_Maceio,
        [PgName("America/Managua")]
        America_Managua,
        [PgName("America/Manaus")]
        America_Manaus,
        [PgName("America/Marigot")]
        America_Marigot,
        [PgName("America/Martinique")]
        America_Martinique,
        [PgName("America/Matamoros")]
        America_Matamoros,
        [PgName("America/Mazatlan")]
        America_Mazatlan,
        [PgName("America/Mendoza")]
        America_Mendoza,
        [PgName("America/Menominee")]
        America_Menominee,
        [PgName("America/Merida")]
        America_Merida,
        [PgName("America/Metlakatla")]
        America_Metlakatla,
        [PgName("America/Mexico_City")]
        America_Mexico_City,
        [PgName("America/Miquelon")]
        America_Miquelon,
        [PgName("America/Moncton")]
        America_Moncton,
        [PgName("America/Monterrey")]
        America_Monterrey,
        [PgName("America/Montevideo")]
        America_Montevideo,
        [PgName("America/Montreal")]
        America_Montreal,
        [PgName("America/Montserrat")]
        America_Montserrat,
        [PgName("America/Nassau")]
        America_Nassau,
        [PgName("America/New_York")]
        America_New_York,
        [PgName("America/Nipigon")]
        America_Nipigon,
        [PgName("America/Nome")]
        America_Nome,
        [PgName("America/Noronha")]
        America_Noronha,
        [PgName("America/North_Dakota/Beulah")]
        America_North_Dakota_Beulah,
        [PgName("America/North_Dakota/Center")]
        America_North_Dakota_Center,
        [PgName("America/North_Dakota/New_Salem")]
        America_North_Dakota_New_Salem,
        [PgName("America/Ojinaga")]
        America_Ojinaga,
        [PgName("America/Panama")]
        America_Panama,
        [PgName("America/Pangnirtung")]
        America_Pangnirtung,
        [PgName("America/Paramaribo")]
        America_Paramaribo,
        [PgName("America/Phoenix")]
        America_Phoenix,
        [PgName("America/Port-au-Prince")]
        America_Port_au_Prince,
        [PgName("America/Porto_Acre")]
        America_Porto_Acre,
        [PgName("America/Porto_Velho")]
        America_Porto_Velho,
        [PgName("America/Port_of_Spain")]
        America_Port_of_Spain,
        [PgName("America/Puerto_Rico")]
        America_Puerto_Rico,
        [PgName("America/Punta_Arenas")]
        America_Punta_Arenas,
        [PgName("America/Rainy_River")]
        America_Rainy_River,
        [PgName("America/Rankin_Inlet")]
        America_Rankin_Inlet,
        [PgName("America/Recife")]
        America_Recife,
        [PgName("America/Regina")]
        America_Regina,
        [PgName("America/Resolute")]
        America_Resolute,
        [PgName("America/Rio_Branco")]
        America_Rio_Branco,
        [PgName("America/Rosario")]
        America_Rosario,
        [PgName("America/Santarem")]
        America_Santarem,
        [PgName("America/Santa_Isabel")]
        America_Santa_Isabel,
        [PgName("America/Santiago")]
        America_Santiago,
        [PgName("America/Santo_Domingo")]
        America_Santo_Domingo,
        [PgName("America/Sao_Paulo")]
        America_Sao_Paulo,
        [PgName("America/Scoresbysund")]
        America_Scoresbysund,
        [PgName("America/Shiprock")]
        America_Shiprock,
        [PgName("America/Sitka")]
        America_Sitka,
        [PgName("America/St_Barthelemy")]
        America_St_Barthelemy,
        [PgName("America/St_Johns")]
        America_St_Johns,
        [PgName("America/St_Kitts")]
        America_St_Kitts,
        [PgName("America/St_Lucia")]
        America_St_Lucia,
        [PgName("America/St_Thomas")]
        America_St_Thomas,
        [PgName("America/St_Vincent")]
        America_St_Vincent,
        [PgName("America/Swift_Current")]
        America_Swift_Current,
        [PgName("America/Tegucigalpa")]
        America_Tegucigalpa,
        [PgName("America/Thule")]
        America_Thule,
        [PgName("America/Thunder_Bay")]
        America_Thunder_Bay,
        [PgName("America/Tijuana")]
        America_Tijuana,
        [PgName("America/Toronto")]
        America_Toronto,
        [PgName("America/Tortola")]
        America_Tortola,
        [PgName("America/Vancouver")]
        America_Vancouver,
        [PgName("America/Virgin")]
        America_Virgin,
        [PgName("America/Whitehorse")]
        America_Whitehorse,
        [PgName("America/Winnipeg")]
        America_Winnipeg,
        [PgName("America/Yakutat")]
        America_Yakutat,
        [PgName("America/Yellowknife")]
        America_Yellowknife,
        [PgName("Antarctica/Casey")]
        Antarctica_Casey,
        [PgName("Antarctica/Davis")]
        Antarctica_Davis,
        [PgName("Antarctica/DumontDUrville")]
        Antarctica_DumontDUrville,
        [PgName("Antarctica/Macquarie")]
        Antarctica_Macquarie,
        [PgName("Antarctica/Mawson")]
        Antarctica_Mawson,
        [PgName("Antarctica/McMurdo")]
        Antarctica_McMurdo,
        [PgName("Antarctica/Palmer")]
        Antarctica_Palmer,
        [PgName("Antarctica/Rothera")]
        Antarctica_Rothera,
        [PgName("Antarctica/South_Pole")]
        Antarctica_South_Pole,
        [PgName("Antarctica/Syowa")]
        Antarctica_Syowa,
        [PgName("Antarctica/Troll")]
        Antarctica_Troll,
        [PgName("Antarctica/Vostok")]
        Antarctica_Vostok,
        [PgName("Arctic/Longyearbyen")]
        Arctic_Longyearbyen,
        [PgName("Asia/Aden")]
        Asia_Aden,
        [PgName("Asia/Almaty")]
        Asia_Almaty,
        [PgName("Asia/Amman")]
        Asia_Amman,
        [PgName("Asia/Anadyr")]
        Asia_Anadyr,
        [PgName("Asia/Aqtau")]
        Asia_Aqtau,
        [PgName("Asia/Aqtobe")]
        Asia_Aqtobe,
        [PgName("Asia/Ashgabat")]
        Asia_Ashgabat,
        [PgName("Asia/Ashkhabad")]
        Asia_Ashkhabad,
        [PgName("Asia/Atyrau")]
        Asia_Atyrau,
        [PgName("Asia/Baghdad")]
        Asia_Baghdad,
        [PgName("Asia/Bahrain")]
        Asia_Bahrain,
        [PgName("Asia/Baku")]
        Asia_Baku,
        [PgName("Asia/Bangkok")]
        Asia_Bangkok,
        [PgName("Asia/Barnaul")]
        Asia_Barnaul,
        [PgName("Asia/Beirut")]
        Asia_Beirut,
        [PgName("Asia/Bishkek")]
        Asia_Bishkek,
        [PgName("Asia/Brunei")]
        Asia_Brunei,
        [PgName("Asia/Calcutta")]
        Asia_Calcutta,
        [PgName("Asia/Chita")]
        Asia_Chita,
        [PgName("Asia/Choibalsan")]
        Asia_Choibalsan,
        [PgName("Asia/Chongqing")]
        Asia_Chongqing,
        [PgName("Asia/Chungking")]
        Asia_Chungking,
        [PgName("Asia/Colombo")]
        Asia_Colombo,
        [PgName("Asia/Dacca")]
        Asia_Dacca,
        [PgName("Asia/Damascus")]
        Asia_Damascus,
        [PgName("Asia/Dhaka")]
        Asia_Dhaka,
        [PgName("Asia/Dili")]
        Asia_Dili,
        [PgName("Asia/Dubai")]
        Asia_Dubai,
        [PgName("Asia/Dushanbe")]
        Asia_Dushanbe,
        [PgName("Asia/Famagusta")]
        Asia_Famagusta,
        [PgName("Asia/Gaza")]
        Asia_Gaza,
        [PgName("Asia/Harbin")]
        Asia_Harbin,
        [PgName("Asia/Hebron")]
        Asia_Hebron,
        [PgName("Asia/Hong_Kong")]
        Asia_Hong_Kong,
        [PgName("Asia/Hovd")]
        Asia_Hovd,
        [PgName("Asia/Ho_Chi_Minh")]
        Asia_Ho_Chi_Minh,
        [PgName("Asia/Irkutsk")]
        Asia_Irkutsk,
        [PgName("Asia/Istanbul")]
        Asia_Istanbul,
        [PgName("Asia/Jakarta")]
        Asia_Jakarta,
        [PgName("Asia/Jayapura")]
        Asia_Jayapura,
        [PgName("Asia/Jerusalem")]
        Asia_Jerusalem,
        [PgName("Asia/Kabul")]
        Asia_Kabul,
        [PgName("Asia/Kamchatka")]
        Asia_Kamchatka,
        [PgName("Asia/Karachi")]
        Asia_Karachi,
        [PgName("Asia/Kashgar")]
        Asia_Kashgar,
        [PgName("Asia/Kathmandu")]
        Asia_Kathmandu,
        [PgName("Asia/Katmandu")]
        Asia_Katmandu,
        [PgName("Asia/Khandyga")]
        Asia_Khandyga,
        [PgName("Asia/Kolkata")]
        Asia_Kolkata,
        [PgName("Asia/Krasnoyarsk")]
        Asia_Krasnoyarsk,
        [PgName("Asia/Kuala_Lumpur")]
        Asia_Kuala_Lumpur,
        [PgName("Asia/Kuching")]
        Asia_Kuching,
        [PgName("Asia/Kuwait")]
        Asia_Kuwait,
        [PgName("Asia/Macao")]
        Asia_Macao,
        [PgName("Asia/Macau")]
        Asia_Macau,
        [PgName("Asia/Magadan")]
        Asia_Magadan,
        [PgName("Asia/Makassar")]
        Asia_Makassar,
        [PgName("Asia/Manila")]
        Asia_Manila,
        [PgName("Asia/Muscat")]
        Asia_Muscat,
        [PgName("Asia/Nicosia")]
        Asia_Nicosia,
        [PgName("Asia/Novokuznetsk")]
        Asia_Novokuznetsk,
        [PgName("Asia/Novosibirsk")]
        Asia_Novosibirsk,
        [PgName("Asia/Omsk")]
        Asia_Omsk,
        [PgName("Asia/Oral")]
        Asia_Oral,
        [PgName("Asia/Phnom_Penh")]
        Asia_Phnom_Penh,
        [PgName("Asia/Pontianak")]
        Asia_Pontianak,
        [PgName("Asia/Pyongyang")]
        Asia_Pyongyang,
        [PgName("Asia/Qatar")]
        Asia_Qatar,
        [PgName("Asia/Qostanay")]
        Asia_Qostanay,
        [PgName("Asia/Qyzylorda")]
        Asia_Qyzylorda,
        [PgName("Asia/Rangoon")]
        Asia_Rangoon,
        [PgName("Asia/Riyadh")]
        Asia_Riyadh,
        [PgName("Asia/Saigon")]
        Asia_Saigon,
        [PgName("Asia/Sakhalin")]
        Asia_Sakhalin,
        [PgName("Asia/Samarkand")]
        Asia_Samarkand,
        [PgName("Asia/Seoul")]
        Asia_Seoul,
        [PgName("Asia/Shanghai")]
        Asia_Shanghai,
        [PgName("Asia/Singapore")]
        Asia_Singapore,
        [PgName("Asia/Srednekolymsk")]
        Asia_Srednekolymsk,
        [PgName("Asia/Taipei")]
        Asia_Taipei,
        [PgName("Asia/Tashkent")]
        Asia_Tashkent,
        [PgName("Asia/Tbilisi")]
        Asia_Tbilisi,
        [PgName("Asia/Tehran")]
        Asia_Tehran,
        [PgName("Asia/Tel_Aviv")]
        Asia_Tel_Aviv,
        [PgName("Asia/Thimbu")]
        Asia_Thimbu,
        [PgName("Asia/Thimphu")]
        Asia_Thimphu,
        [PgName("Asia/Tokyo")]
        Asia_Tokyo,
        [PgName("Asia/Tomsk")]
        Asia_Tomsk,
        [PgName("Asia/Ujung_Pandang")]
        Asia_Ujung_Pandang,
        [PgName("Asia/Ulaanbaatar")]
        Asia_Ulaanbaatar,
        [PgName("Asia/Ulan_Bator")]
        Asia_Ulan_Bator,
        [PgName("Asia/Urumqi")]
        Asia_Urumqi,
        [PgName("Asia/Ust-Nera")]
        Asia_Ust_Nera,
        [PgName("Asia/Vientiane")]
        Asia_Vientiane,
        [PgName("Asia/Vladivostok")]
        Asia_Vladivostok,
        [PgName("Asia/Yakutsk")]
        Asia_Yakutsk,
        [PgName("Asia/Yangon")]
        Asia_Yangon,
        [PgName("Asia/Yekaterinburg")]
        Asia_Yekaterinburg,
        [PgName("Asia/Yerevan")]
        Asia_Yerevan,
        [PgName("Atlantic/Azores")]
        Atlantic_Azores,
        [PgName("Atlantic/Bermuda")]
        Atlantic_Bermuda,
        [PgName("Atlantic/Canary")]
        Atlantic_Canary,
        [PgName("Atlantic/Cape_Verde")]
        Atlantic_Cape_Verde,
        [PgName("Atlantic/Faeroe")]
        Atlantic_Faeroe,
        [PgName("Atlantic/Faroe")]
        Atlantic_Faroe,
        [PgName("Atlantic/Jan_Mayen")]
        Atlantic_Jan_Mayen,
        [PgName("Atlantic/Madeira")]
        Atlantic_Madeira,
        [PgName("Atlantic/Reykjavik")]
        Atlantic_Reykjavik,
        [PgName("Atlantic/South_Georgia")]
        Atlantic_South_Georgia,
        [PgName("Atlantic/Stanley")]
        Atlantic_Stanley,
        [PgName("Atlantic/St_Helena")]
        Atlantic_St_Helena,
        [PgName("Australia/ACT")]
        Australia_ACT,
        [PgName("Australia/Adelaide")]
        Australia_Adelaide,
        [PgName("Australia/Brisbane")]
        Australia_Brisbane,
        [PgName("Australia/Broken_Hill")]
        Australia_Broken_Hill,
        [PgName("Australia/Canberra")]
        Australia_Canberra,
        [PgName("Australia/Currie")]
        Australia_Currie,
        [PgName("Australia/Darwin")]
        Australia_Darwin,
        [PgName("Australia/Eucla")]
        Australia_Eucla,
        [PgName("Australia/Hobart")]
        Australia_Hobart,
        [PgName("Australia/LHI")]
        Australia_LHI,
        [PgName("Australia/Lindeman")]
        Australia_Lindeman,
        [PgName("Australia/Lord_Howe")]
        Australia_Lord_Howe,
        [PgName("Australia/Melbourne")]
        Australia_Melbourne,
        [PgName("Australia/North")]
        Australia_North,
        [PgName("Australia/NSW")]
        Australia_NSW,
        [PgName("Australia/Perth")]
        Australia_Perth,
        [PgName("Australia/Queensland")]
        Australia_Queensland,
        [PgName("Australia/South")]
        Australia_South,
        [PgName("Australia/Sydney")]
        Australia_Sydney,
        [PgName("Australia/Tasmania")]
        Australia_Tasmania,
        [PgName("Australia/Victoria")]
        Australia_Victoria,
        [PgName("Australia/West")]
        Australia_West,
        [PgName("Australia/Yancowinna")]
        Australia_Yancowinna,
        [PgName("Brazil/Acre")]
        Brazil_Acre,
        [PgName("Brazil/DeNoronha")]
        Brazil_DeNoronha,
        [PgName("Brazil/East")]
        Brazil_East,
        [PgName("Brazil/West")]
        Brazil_West,
        [PgName("Canada/Atlantic")]
        Canada_Atlantic,
        [PgName("Canada/Central")]
        Canada_Central,
        [PgName("Canada/Eastern")]
        Canada_Eastern,
        [PgName("Canada/Mountain")]
        Canada_Mountain,
        [PgName("Canada/Newfoundland")]
        Canada_Newfoundland,
        [PgName("Canada/Pacific")]
        Canada_Pacific,
        [PgName("Canada/Saskatchewan")]
        Canada_Saskatchewan,
        [PgName("Canada/Yukon")]
        Canada_Yukon,
        [PgName("CET")]
        CET,
        [PgName("Chile/Continental")]
        Chile_Continental,
        [PgName("Chile/EasterIsland")]
        Chile_EasterIsland,
        [PgName("CST6CDT")]
        CST6CDT,
        [PgName("Cuba")]
        Cuba,
        [PgName("EET")]
        EET,
        [PgName("Egypt")]
        Egypt,
        [PgName("Eire")]
        Eire,
        [PgName("EST")]
        EST,
        [PgName("EST5EDT")]
        EST5EDT,
        [PgName("Etc/GMT")]
        Etc_GMT,
        [PgName("Etc/GMT+0")]
        Etc_GMT_plus_0,
        [PgName("Etc/GMT+1")]
        Etc_GMT_plus_1,
        [PgName("Etc/GMT+10")]
        Etc_GMT_plus_10,
        [PgName("Etc/GMT+11")]
        Etc_GMT_plus_11,
        [PgName("Etc/GMT+12")]
        Etc_GMT_plus_12,
        [PgName("Etc/GMT+2")]
        Etc_GMT_plus_2,
        [PgName("Etc/GMT+3")]
        Etc_GMT_plus_3,
        [PgName("Etc/GMT+4")]
        Etc_GMT_plus_4,
        [PgName("Etc/GMT+5")]
        Etc_GMT_plus_5,
        [PgName("Etc/GMT+6")]
        Etc_GMT_plus_6,
        [PgName("Etc/GMT+7")]
        Etc_GMT_plus_7,
        [PgName("Etc/GMT+8")]
        Etc_GMT_plus_8,
        [PgName("Etc/GMT+9")]
        Etc_GMT_plus_9,
        [PgName("Etc/GMT-0")]
        Etc_GMT_minus_0,
        [PgName("Etc/GMT-1")]
        Etc_GMT_minus_1,
        [PgName("Etc/GMT-10")]
        Etc_GMT_minus_10,
        [PgName("Etc/GMT-11")]
        Etc_GMT_minus_11,
        [PgName("Etc/GMT-12")]
        Etc_GMT_minus_12,
        [PgName("Etc/GMT-13")]
        Etc_GMT_minus_13,
        [PgName("Etc/GMT-14")]
        Etc_GMT_minus_14,
        [PgName("Etc/GMT-2")]
        Etc_GMT_minus_2,
        [PgName("Etc/GMT-3")]
        Etc_GMT_minus_3,
        [PgName("Etc/GMT-4")]
        Etc_GMT_minus_4,
        [PgName("Etc/GMT-5")]
        Etc_GMT_minus_5,
        [PgName("Etc/GMT-6")]
        Etc_GMT_minus_6,
        [PgName("Etc/GMT-7")]
        Etc_GMT_minus_7,
        [PgName("Etc/GMT-8")]
        Etc_GMT_minus_8,
        [PgName("Etc/GMT-9")]
        Etc_GMT_minus_9,
        [PgName("Etc/GMT0")]
        Etc_GMT0,
        [PgName("Etc/Greenwich")]
        Etc_Greenwich,
        [PgName("Etc/UCT")]
        Etc_UCT,
        [PgName("Etc/Universal")]
        Etc_Universal,
        [PgName("Etc/UTC")]
        Etc_UTC,
        [PgName("Etc/Zulu")]
        Etc_Zulu,
        [PgName("Europe/Amsterdam")]
        Europe_Amsterdam,
        [PgName("Europe/Andorra")]
        Europe_Andorra,
        [PgName("Europe/Astrakhan")]
        Europe_Astrakhan,
        [PgName("Europe/Athens")]
        Europe_Athens,
        [PgName("Europe/Belfast")]
        Europe_Belfast,
        [PgName("Europe/Belgrade")]
        Europe_Belgrade,
        [PgName("Europe/Berlin")]
        Europe_Berlin,
        [PgName("Europe/Bratislava")]
        Europe_Bratislava,
        [PgName("Europe/Brussels")]
        Europe_Brussels,
        [PgName("Europe/Bucharest")]
        Europe_Bucharest,
        [PgName("Europe/Budapest")]
        Europe_Budapest,
        [PgName("Europe/Busingen")]
        Europe_Busingen,
        [PgName("Europe/Chisinau")]
        Europe_Chisinau,
        [PgName("Europe/Copenhagen")]
        Europe_Copenhagen,
        [PgName("Europe/Dublin")]
        Europe_Dublin,
        [PgName("Europe/Gibraltar")]
        Europe_Gibraltar,
        [PgName("Europe/Guernsey")]
        Europe_Guernsey,
        [PgName("Europe/Helsinki")]
        Europe_Helsinki,
        [PgName("Europe/Isle_of_Man")]
        Europe_Isle_of_Man,
        [PgName("Europe/Istanbul")]
        Europe_Istanbul,
        [PgName("Europe/Jersey")]
        Europe_Jersey,
        [PgName("Europe/Kaliningrad")]
        Europe_Kaliningrad,
        [PgName("Europe/Kiev")]
        Europe_Kiev,
        [PgName("Europe/Kirov")]
        Europe_Kirov,
        [PgName("Europe/Lisbon")]
        Europe_Lisbon,
        [PgName("Europe/Ljubljana")]
        Europe_Ljubljana,
        [PgName("Europe/London")]
        Europe_London,
        [PgName("Europe/Luxembourg")]
        Europe_Luxembourg,
        [PgName("Europe/Madrid")]
        Europe_Madrid,
        [PgName("Europe/Malta")]
        Europe_Malta,
        [PgName("Europe/Mariehamn")]
        Europe_Mariehamn,
        [PgName("Europe/Minsk")]
        Europe_Minsk,
        [PgName("Europe/Monaco")]
        Europe_Monaco,
        [PgName("Europe/Moscow")]
        Europe_Moscow,
        [PgName("Europe/Nicosia")]
        Europe_Nicosia,
        [PgName("Europe/Oslo")]
        Europe_Oslo,
        [PgName("Europe/Paris")]
        Europe_Paris,
        [PgName("Europe/Podgorica")]
        Europe_Podgorica,
        [PgName("Europe/Prague")]
        Europe_Prague,
        [PgName("Europe/Riga")]
        Europe_Riga,
        [PgName("Europe/Rome")]
        Europe_Rome,
        [PgName("Europe/Samara")]
        Europe_Samara,
        [PgName("Europe/San_Marino")]
        Europe_San_Marino,
        [PgName("Europe/Sarajevo")]
        Europe_Sarajevo,
        [PgName("Europe/Saratov")]
        Europe_Saratov,
        [PgName("Europe/Simferopol")]
        Europe_Simferopol,
        [PgName("Europe/Skopje")]
        Europe_Skopje,
        [PgName("Europe/Sofia")]
        Europe_Sofia,
        [PgName("Europe/Stockholm")]
        Europe_Stockholm,
        [PgName("Europe/Tallinn")]
        Europe_Tallinn,
        [PgName("Europe/Tirane")]
        Europe_Tirane,
        [PgName("Europe/Tiraspol")]
        Europe_Tiraspol,
        [PgName("Europe/Ulyanovsk")]
        Europe_Ulyanovsk,
        [PgName("Europe/Uzhgorod")]
        Europe_Uzhgorod,
        [PgName("Europe/Vaduz")]
        Europe_Vaduz,
        [PgName("Europe/Vatican")]
        Europe_Vatican,
        [PgName("Europe/Vienna")]
        Europe_Vienna,
        [PgName("Europe/Vilnius")]
        Europe_Vilnius,
        [PgName("Europe/Volgograd")]
        Europe_Volgograd,
        [PgName("Europe/Warsaw")]
        Europe_Warsaw,
        [PgName("Europe/Zagreb")]
        Europe_Zagreb,
        [PgName("Europe/Zaporozhye")]
        Europe_Zaporozhye,
        [PgName("Europe/Zurich")]
        Europe_Zurich,
        [PgName("GB")]
        GB,
        [PgName("GB-Eire")]
        GB_Eire,
        [PgName("GMT")]
        GMT,
        [PgName("GMT+0")]
        GMT_plus_0,
        [PgName("GMT-0")]
        GMT_minus_0,
        [PgName("GMT0")]
        GMT0,
        [PgName("Greenwich")]
        Greenwich,
        [PgName("Hongkong")]
        Hongkong,
        [PgName("HST")]
        HST,
        [PgName("Iceland")]
        Iceland,
        [PgName("Indian/Antananarivo")]
        Indian_Antananarivo,
        [PgName("Indian/Chagos")]
        Indian_Chagos,
        [PgName("Indian/Christmas")]
        Indian_Christmas,
        [PgName("Indian/Cocos")]
        Indian_Cocos,
        [PgName("Indian/Comoro")]
        Indian_Comoro,
        [PgName("Indian/Kerguelen")]
        Indian_Kerguelen,
        [PgName("Indian/Mahe")]
        Indian_Mahe,
        [PgName("Indian/Maldives")]
        Indian_Maldives,
        [PgName("Indian/Mauritius")]
        Indian_Mauritius,
        [PgName("Indian/Mayotte")]
        Indian_Mayotte,
        [PgName("Indian/Reunion")]
        Indian_Reunion,
        [PgName("Iran")]
        Iran,
        [PgName("Israel")]
        Israel,
        [PgName("Jamaica")]
        Jamaica,
        [PgName("Japan")]
        Japan,
        [PgName("Kwajalein")]
        Kwajalein,
        [PgName("Libya")]
        Libya,
        [PgName("MET")]
        MET,
        [PgName("Mexico/BajaNorte")]
        Mexico_BajaNorte,
        [PgName("Mexico/BajaSur")]
        Mexico_BajaSur,
        [PgName("Mexico/General")]
        Mexico_General,
        [PgName("MST")]
        MST,
        [PgName("MST7MDT")]
        MST7MDT,
        [PgName("Navajo")]
        Navajo,
        [PgName("NZ")]
        NZ,
        [PgName("NZ-CHAT")]
        NZ_CHAT,
        [PgName("Pacific/Apia")]
        Pacific_Apia,
        [PgName("Pacific/Auckland")]
        Pacific_Auckland,
        [PgName("Pacific/Bougainville")]
        Pacific_Bougainville,
        [PgName("Pacific/Chatham")]
        Pacific_Chatham,
        [PgName("Pacific/Chuuk")]
        Pacific_Chuuk,
        [PgName("Pacific/Easter")]
        Pacific_Easter,
        [PgName("Pacific/Efate")]
        Pacific_Efate,
        [PgName("Pacific/Enderbury")]
        Pacific_Enderbury,
        [PgName("Pacific/Fakaofo")]
        Pacific_Fakaofo,
        [PgName("Pacific/Fiji")]
        Pacific_Fiji,
        [PgName("Pacific/Funafuti")]
        Pacific_Funafuti,
        [PgName("Pacific/Galapagos")]
        Pacific_Galapagos,
        [PgName("Pacific/Gambier")]
        Pacific_Gambier,
        [PgName("Pacific/Guadalcanal")]
        Pacific_Guadalcanal,
        [PgName("Pacific/Guam")]
        Pacific_Guam,
        [PgName("Pacific/Honolulu")]
        Pacific_Honolulu,
        [PgName("Pacific/Johnston")]
        Pacific_Johnston,
        [PgName("Pacific/Kiritimati")]
        Pacific_Kiritimati,
        [PgName("Pacific/Kosrae")]
        Pacific_Kosrae,
        [PgName("Pacific/Kwajalein")]
        Pacific_Kwajalein,
        [PgName("Pacific/Majuro")]
        Pacific_Majuro,
        [PgName("Pacific/Marquesas")]
        Pacific_Marquesas,
        [PgName("Pacific/Midway")]
        Pacific_Midway,
        [PgName("Pacific/Nauru")]
        Pacific_Nauru,
        [PgName("Pacific/Niue")]
        Pacific_Niue,
        [PgName("Pacific/Norfolk")]
        Pacific_Norfolk,
        [PgName("Pacific/Noumea")]
        Pacific_Noumea,
        [PgName("Pacific/Pago_Pago")]
        Pacific_Pago_Pago,
        [PgName("Pacific/Palau")]
        Pacific_Palau,
        [PgName("Pacific/Pitcairn")]
        Pacific_Pitcairn,
        [PgName("Pacific/Pohnpei")]
        Pacific_Pohnpei,
        [PgName("Pacific/Ponape")]
        Pacific_Ponape,
        [PgName("Pacific/Port_Moresby")]
        Pacific_Port_Moresby,
        [PgName("Pacific/Rarotonga")]
        Pacific_Rarotonga,
        [PgName("Pacific/Saipan")]
        Pacific_Saipan,
        [PgName("Pacific/Samoa")]
        Pacific_Samoa,
        [PgName("Pacific/Tahiti")]
        Pacific_Tahiti,
        [PgName("Pacific/Tarawa")]
        Pacific_Tarawa,
        [PgName("Pacific/Tongatapu")]
        Pacific_Tongatapu,
        [PgName("Pacific/Truk")]
        Pacific_Truk,
        [PgName("Pacific/Wake")]
        Pacific_Wake,
        [PgName("Pacific/Wallis")]
        Pacific_Wallis,
        [PgName("Pacific/Yap")]
        Pacific_Yap,
        [PgName("Poland")]
        Poland,
        [PgName("Portugal")]
        Portugal,
        [PgName("PRC")]
        PRC,
        [PgName("PST8PDT")]
        PST8PDT,
        [PgName("ROC")]
        ROC,
        [PgName("ROK")]
        ROK,
        [PgName("Singapore")]
        Singapore,
        [PgName("Turkey")]
        Turkey,
        [PgName("UCT")]
        UCT,
        [PgName("Universal")]
        Universal,
        [PgName("US/Alaska")]
        US_Alaska,
        [PgName("US/Aleutian")]
        US_Aleutian,
        [PgName("US/Arizona")]
        US_Arizona,
        [PgName("US/Central")]
        US_Central,
        [PgName("US/East-Indiana")]
        US_East_Indiana,
        [PgName("US/Eastern")]
        US_Eastern,
        [PgName("US/Hawaii")]
        US_Hawaii,
        [PgName("US/Indiana-Starke")]
        US_Indiana_Starke,
        [PgName("US/Michigan")]
        US_Michigan,
        [PgName("US/Mountain")]
        US_Mountain,
        [PgName("US/Pacific")]
        US_Pacific,
        [PgName("US/Samoa")]
        US_Samoa,
        [PgName("UTC")]
        UTC,
        [PgName("W-SU")]
        W_SU,
        [PgName("WET")]
        WET,
        [PgName("Zulu")]
        Zulu
    }
}
